---
# Playbook to install development tools on localhost
# This playbook installs Bash-it and Terraform

- name: Install Bash-it
  hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - role: ../roles/install-bash_it

- name: Install Terraform
  hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - role: ../roles/install-terraform

- name: disable-ipv6
  hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - role: ../roles/disable-ipv6

- name: Install Packer
  hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - role: ../roles/install-packer
...